### ISSUE TITLE
Maximum bandwidth configurable

### ISSUE THREAD

**Issue by Beejeedeb** [mozilla-iot/speed-test-adapter#2]
Hello,

Is it possible to make maximum bandwidth of the Internet connection configurable via the configure menu with a value in Megabps? Now it is a static value of 10000 which means that the levelproperty gauge is always empty.

![downloadspeed](https://user-images.githubusercontent.com/51539492/63654264-7dacf280-c778-11e9-8dc2-c12d7cddb456.png)

**Comment by mrstegeman** [comment]
The download speed property shouldn't really be a LevelProperty at all. It should just be a generic number property. The only reason I made it a LevelProperty was so I could use the MultiLevelSensor capability (such that the bandwidth would show on the primary icon).

I definitely understand your reasoning, but I think adding this setting would really just be confusing to typical users.

I'm hoping that in the near future, add-ons will have the ability to bring along their own UI components. If/when that happens, I'll make this add-on stop abusing the schemas.
